version: '3'

services:
  freshly-fit-website-env-testing:
    build:
      context: ../../
      dockerfile: docker/testing/Dockerfile
    image: freshly-fit-website-env-testing
    env_file:
      - ../../.env.test
    ports:
      - ${FRESHLY_FIT_WEBSITE_TESTING_EXPOSED_PORT}:8092
